"""Add color

Revision ID: 24ae958849b9
Revises: cb795131ff7a
Create Date: 2025-05-05 12:27:44.636227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24ae958849b9'
down_revision = 'cb795131ff7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('DONE', 'PENDING', 'MISSED', 'REMINDED', name='status'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('DONE', 'PENDING', 'MISSED', 'REMINDED', name='status'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)

    # ### end Alembic commands ###
